### ISSUE TITLE
Timelapse / EON processes not running when Day disabled

### ISSUE THREAD

**Issue by p1ntobean** [aaronwmorris/indi-allsky#219] opened 2022-06-15 17:08 UTC
With day capture and day timelapse disabled, no end of night or night timelapse is being generated.  The logs do not show any errors nor do the processes queue or fire.  If Day capture and Day Timelapse is enabled, a Day timelapse is generated at end of day but still no end of night process.

Attached is a peek at the log file showing the last night image capture, then immediate switch to day mode and no further night processes.  Additional items of note:

1. VideoWorker process does start at boot time and generates no errors
2. Manual kicking of the generateNightTimelapse  says it runs and doesn't throw any errors, but it does not produce an output

Jun 15 05:53:09 allskypi [INFO] FileUploader001 uploader.run() #201: Upload transaction completed in 0.2132 s
Jun 15 05:53:16 allskypi [INFO] MainProcess allsky.run() #596: Camera last ready: 10.1s
Jun 15 05:53:16 allskypi [INFO] MainProcess allsky.run() #597: Exposure state: OK
Jun 15 05:53:16 allskypi [INFO] MainProcess allsky.detectNight() #835: Sun altitude: -5:58:11.5
Jun 15 05:53:16 allskypi [INFO] MainProcess allsky.detectMoonMode() #852: Moon altitide: 13:17:38.1, phase 98.5%
Jun 15 05:53:16 allskypi [INFO] MainProcess allsky.run() #610: Daytime capture is disabled

**Comment by aaronwmorris** [comment] 2022-06-15 17:28
Okay, my theory is that the VideoWorker is running into an exception that is not being logged.  Python multiprocessing makes logging overly complicated and I am still trying to track down how to get exceptions logged properly.

What I would like you do do is stop the indi-allsky service and run it from the CLI.  In a second session, try to generate the timelapse.  Hopefully, the exception should be logged in the first session.


First session
```
systemctl --user stop indi-allsky

source virtualenv/indi-allsky/bin/activate
./allsky.py run
```

Second session
```
source virtualenv/indi-allsky/bin/activate
./allsky.py generateNightTimelapse --timespec 20220613
```

See if any exceptions are generated in the first session.  You may experience double logging, which is yet another issue I am tracking down.

**Comment by p1ntobean** [comment] 2022-06-15 19:10
Thank you - unfortunately nothing was caught in the first session.  Like 
before, running the timelapse directly "appears" to go ok in the second 
session but it's never actually queued or run.

I tried this on the original Pi install (which had the 20220613 image 
folders) and on the new Pi (updating timespec for 20220614

First session, zero messages or notices when executing the second 
session.  Nothing:

[2022-06-15 14:02:07,894] INFO in allsky: Moon altitide: -80:05:24.0, 
phase 97.3%
2022-06-15 14:02:07,895 [INFO] MainProcess allsky.run() #610: Daytime 
capture is disabled
[2022-06-15 14:02:07,895] INFO in allsky: Daytime capture is disabled

Second session:

(indi-allsky) ***@***.***:~/indi-allsky $ ./allsky.py 
generateNightTimelapse --timespec 2022613
2022-06-15 14:02:06,893 [WARNING] MainProcess 
allsky._generateNightTimelapse() #939: Generating night time timelapse 
for 2022613 camera 1
[2022-06-15 14:02:06,893] WARNING in allsky: Generating night time 
timelapse for 2022613 camera 1
(indi-allsky) ***@***.***:~/indi-allsky $

On 2022-06-15 12:28, Aaron W Morris wrote:

> Okay, my theory is that the VideoWorker is running into an exception 
> that is not being logged. Python multiprocessing makes logging overly 
> complicated and I am still trying to track down how to get exceptions 
> logged properly.
> 
> What I would like you do do is stop the indi-allsky service and run it 
> from the CLI. In a second session, try to generate the timelapse. 
> Hopefully, the exception should be logged in the first session.
> 
> First session
> 
> systemctl --user stop indi-allsky
> 
> source virtualenv/indi-allsky/bin/activate
> ./allsky.py run
> 
> Second session
> 
> source virtualenv/indi-allsky/bin/activate
> ./allsky.py generateNightTimelapse --timespec 20220613
> 
> See if any exceptions are generated in the first session. You may 
> experience double logging, which is yet another issue I am tracking 
> down.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/aaronwmorris/indi-allsky/issues/219#issuecomment-1156743421
[2]

**Comment by p1ntobean** [comment] 2022-06-15 19:31
Out of curiosity, I tried to generate manually for a future date to see if I could get any log error, that DOES clearly show the manual timelapse process triggers, and it noted the folder didn't exist.

Jun 15 14:15:41 allskypi [INFO] VideoWorker001 video._getLock() #665: Get exclusive lock to generate video
Jun 15 14:15:41 allskypi [ERROR] VideoWorker001 video.run() #139: Image folder does not exist: /var/www/html/allsky/images/2022615/night


I think you are on to something; an error condition is existing somewhere in the process and likely before it even calls the videoworker, at least before it would show up in any logging

**Comment by aaronwmorris** [comment] 2022-06-15 22:36
I am at a bit of a loss.  I am thinking about what could be the issue.

**Comment by p1ntobean** [comment] 2022-06-15 23:02
I probably messed with this more today than I should.

Turned on some traces and dig a little further, managed to get this to 
show:

Traceback (most recent call last):
File "/home/pi/indi-allsky/./allsky.py", line 3, in <module>
import indi_allsky
File "/home/pi/indi-allsky/indi_allsky/__init__.py", line 1, in <module>
from .allsky import IndiAllSky
File "/home/pi/indi-allsky/indi_allsky/allsky.py", line 15, in <module>
import ephem
ModuleNotFoundError: No module named 'ephem'

**Comment by aaronwmorris** [comment] 2022-06-15 23:04
That probably happened because you forgot to activate the virtualenv.

**Comment by p1ntobean** [comment] 2022-06-15 23:25
yes - told you I was messing with it too much.  Disregard.

**Comment by aaronwmorris** [comment] 2022-06-16 15:32
Is it possible you changed something that might have altered the image dimensions for that first night?  If all of the image sizes do not match, then the keogram/timelapse process will utterly fail.

**Comment by p1ntobean** [comment] 2022-06-16 15:50
Not that I am aware of - I did not change any of the defaults for actual 
image generation.

That said, I just checked, and they are all the same but SX Oculus is an 
SXGA format 1392 x 1040.  Maybe it is having trouble with the default 
dimensions and I should make some adjustments there?

**Comment by aaronwmorris** [comment] 2022-06-16 16:01
That should not be a problem... I am still thinking...

**Comment by aaronwmorris** [comment] 2022-06-19 00:23
I recently merged and update that allows you to generate timelapses from the web interface.

**Comment by p1ntobean** [comment] 2022-06-20 20:33
I did a pull and will test it out

**Comment by darkorb** [comment] 2022-08-18 20:46
Hey there, so i appear to have ran into this also. Interestingly when triggering the generation through the WebUI they still fail to run.

```
Aug 19 08:17:18 indi-allsky-proc [WARNING] MainProcess views.dispatch_request() #2237: Generating night time timelapse for 20220814 camera 1
Aug 19 08:17:22 indi-allsky-proc [INFO] MainProcess forms.__init__() #1397: Dates processed in 0.0142 s
Aug 19 08:17:22 indi-allsky-proc [WARNING] MainProcess views.dispatch_request() #2237: Generating night time timelapse for 20220815 camera 1
Aug 19 08:17:24 indi-allsky-proc [INFO] MainProcess forms.__init__() #1397: Dates processed in 0.0144 s
Aug 19 08:17:24 indi-allsky-proc [WARNING] MainProcess views.dispatch_request() #2237: Generating night time timelapse for 20220816 camera 1
Aug 19 08:17:29 indi-allsky-proc [INFO] MainProcess forms.__init__() #1397: Dates processed in 0.0141 s
Aug 19 08:17:29 indi-allsky-proc [WARNING] MainProcess views.dispatch_request() #2237: Generating night time timelapse for 20220818 camera 1
```

Clearly it see's it's being asked to trigger this off but still not doing so. 

Running through the debugging detailed above doesn't render any extra logs really:

```
./allsky.py generateNightTimelapse --timespec 20220814
2022-08-19 08:35:20,438 [WARNING] MainProcess allsky._generateNightTimelapse() #957: Generating night time timelapse for 20220814 camera 1
[2022-08-19 08:35:20,438] WARNING in allsky: Generating night time timelapse for 20220814 camera 1
```
and thus generated in the logging in the other session;
```

```
Yup, nothing 🙃 other logging around the time however are such (these are the ones that appear from time to time anyway):

```
2022-08-19 08:39:46,127 [INFO] MainProcess allsky.run() #607: Camera last ready: 360.2s
[2022-08-19 08:39:46,127] INFO in allsky: Camera last ready: 360.2s
2022-08-19 08:39:46,127 [INFO] MainProcess allsky.run() #608: Exposure state: unset
[2022-08-19 08:39:46,127] INFO in allsky: Exposure state: unset
2022-08-19 08:39:46,127 [INFO] MainProcess allsky.detectNight() #853: Sun altitude: 15:07:22.3
[2022-08-19 08:39:46,127] INFO in allsky: Sun altitude: 15:07:22.3
2022-08-19 08:39:46,127 [INFO] MainProcess allsky.detectMoonMode() #870: Moon altitide: 17:31:38.9, phase 53.2%
[2022-08-19 08:39:46,127] INFO in allsky: Moon altitide: 17:31:38.9, phase 53.2%
2022-08-19 08:39:46,127 [INFO] MainProcess allsky.run() #621: Daytime capture is disabled
[2022-08-19 08:39:46,127] INFO in allsky: Daytime capture is disabled
```

I can confirm that enabling daytime capture and then manually submitting the task works without issue. Any other logging or things you'd like tested? I'll keep mine in a broken state for now (save the one it's generating at the moment) as I don't want to run the camera during the day due to the heat - even though it's winter it's still a bit toasty in the enclosure!

**Comment by aaronwmorris** [comment] 2022-08-18 22:54
Would you be willing to send me your latitude, longitude, and time zone?

I need to get exception logging working.  I think an exception is being generated and we cannot see it.

**Comment by darkorb** [comment] 2022-08-18 23:02
Approx. it's -41.30, 174.73 (Wellington, NZ) so NZST. If you need more accurate than that let me know a non-public way and I can send over.

**Comment by aaronwmorris** [comment] 2022-08-19 00:43
I am sure that is close enough.  There is a small chance this is a location specific problem, but I really doubt it.

**Comment by aaronwmorris** [comment] 2022-08-19 16:45
I have merged #302 to log uncaught exceptions from the worker processes.  I am very interested if an exception is being generated.

**Comment by darkorb** [comment] 2022-08-20 02:40
I gave that a pull and upgrade, unfortunately doesn't appear to be any new errors generated after triggering from the command line. I can see the task in the queue in the WebUI so know it submitted without issue though:

```
(indi-allsky) asmith@indi-allsky-proc:~/indi-allsky$ ./allsky.py generateNightTimelapse --timespec 20220815
2022-08-20 14:30:56,959 [WARNING] MainProcess allsky._generateNightTimelapse() #984: Generating night time timelapse for 20220815 camera 1
[2022-08-20 14:30:56,959] WARNING in allsky: Generating night time timelapse for 20220815 camera 1
```

Nothing really appears in the other log. It's a little longer so I've pasted it to  https://gist.github.com/darkorb/2737a18216bd78fc18dab686b7fef44b

**Comment by pimmoon** [comment] 2022-08-31 14:32
Hi.

I second this. I also see that when I set the "Daytime Capture" to off. I wasn't able to generate timelapse or keogram. I tried this for two days. Tried to run it manually as well. So today I decided to set "Daytime Capture" and "Daytime Timelapse" to on. And now i am able to generate Timelapse, Keogram, and Startails. 

I use ASI120MC-S. Just wanted to report the issue. Thank you.

**Comment by aaronwmorris** [comment] 2022-08-31 15:00
I have run one of my test cameras with Daytime Capture disabled and the night time timelapse is not being generated.  I definitely have a bug in the logic somewhere.

I am looking.

**Comment by aaronwmorris** [comment] 2022-09-02 18:10
Merged #347 to fix the time lapses not being generated when daytime capture was disabled.

I apologize for taking so long in finding this.

**Comment by darkorb** [comment] 2022-09-03 00:33
No need to apologize 😸

I've just updated and it appears to be quite happily eating it's way through the backlog of time-lapse images and such that I just queued - it's 12:27pm right now so definitely working during day time. Thanks for taking the time to dig into it.

**Comment by aaronwmorris** [comment] 2022-10-22 22:05
Closing this issue for now.  Let me know if there is anything else I can do.

**Closed by aaronwmorris** 2022-10-22 22:05 UTC
